
export const ARTIST_TAGS: string[] = [
    "0 (znanimo)", "0002koko", "00047", "01 0219", "013 (hamsasuke)", "0321smith", "0930erina", "0jae", "1=2", "1041 (toshikazu)",
    "10mo", "122pxsheol", "13 (bbr584607091)", "1ssakawaguchi", "28 (282teeth)", "38 (sanjuuhachi)", "4qw5", "5t (5t 000)", "7010",
    "748cm", "9474s0ul", "96yottea", "987645321o", "9twoeight", "a-ka", "aaaa (quad-a)", "aamond", "achan (blue semi)",
    "abbystea", "adpx", "aenaluck", "aetherion", "afrobull", "agawa ryou", "ainimo5", "akableak", "akai sashimi", "akakura", "akazawa red",
    "akechi (826988799)", "aki (bekei)", "akihare", "akihazama", "akijin", "akina tsukako", "akino ell", "akipeko", "akita hika", "akitsuki itsuki",
    "akiyama enma", "akiyasu", "akni", "alchemaniac", "alber", "aleriia v", "alex (alexandoria)", "alex ahad", "alexmaster", "almondman",
    "alp", "alphonse (white datura)", "alzi xiaomi", "ama mitsuki", "amagi hana", "amagi shino", "amagasa yun", "amakawa sakko", "amakusa (hidorozoa)",
    "ameto yuki", "ame (uten cancel)", "anmi", "ancotaku", "anderson m0311", "anima miko", "anniechromes", "anno aano", "anno masato", "anny (yoai)",
    "anzu ame", "aoi ogata", "aoi tori", "aoki ume", "aonori misuji", "aoiro oto", "aono shimo", "aozora market", "ap cammy", "appleq",
    "ar (lover boy)", "araneesama", "arata iri", "aria (ariacue)", "arikomen", "arisaka ako", "ario", "aroma sensei", "arsenixc", "art of neigh",
    "artpatient", "arutera", "as109", "asada hachi", "asakura sakura", "asanagi", "ashishun", "asou (asabu202)", "ask (askzy)", "aspara",
    "astg", "asuka shirou", "asura (asurauser)", "atie1225", "atsumisu", "au (d elete)", "auguste", "aurahack", "ayo (ayosanri009)", "ayo rimaisu",
    "aya shobon", "ayu (mog)", "azuumori", "baek hyang", "baffu", "bai qi-qsr", "bacheally", "banpai akira", "barasui",
    "bbc-chan", "bbybluemochi", "bee (deadflow)", "bingansuan jiamouren", "blackbox (blackbox9158)", "blade (galaxist)", "blanclauz", "blaze (blazeillust)",
    "bleedman", "blue gk", "bluekomadori", "blushyspicy", "bm94199", "bonjourdraws", "boshi (a-ieba)", "brassica", "brll", "buchi (qooo003)",
    "busujima (kusahana)", "butcha-u", "butterchalk", "byakuya reki", "c.cu", "cabronpr", "cafin", "cake mogo", "carrot (robosquat)", "catsmoon",
    "cbmus", "cha goma", "chamchami", "chamuring", "channel (caststation)", "chanta (ayatakaoisii)", "chalseu", "cheshirrr", "chihiro (kemonomichi)",
    "chimmyming", "chiroshiron", "chomoran", "choujiroo", "chuzenji", "cierra (ra-bit)", "ciloranko", "cinnabus", "cirenk", "clivenzu", "cogecha",
    "collagen", "controlline3", "cool-kyou shinja", "crimson comics", "criis-chan", "csyday", "cui suika", "cutesexyrobutts", "cyancapsule",
    "dadijiji", "daeho cha", "dakusuta", "dana (ocana dana)", "daniel deng", "dave rapoza", "diathorn", "difman", "dino (dinoartforame)", "dio nand",
    "dishing", "dishwasher1910", "doppel (bonnypir)", "doremi (doremi4704)", "dorontabi", "dr graevling", "ebifurya", "ebiblue", "eerisyn",
    "enpe", "eonsang", "evinist", "f.w.zholic", "falken (yutozin)", "fei (maidoll)", "feint721", "feipin zhanshi", "fellatrix", "fkey", "fuka (hk nemo)",
    "fugtrup", "fujisaka kimihiko", "fujiyama", "fuyukayui", "gashi-gashi", "gearous", "gloss (hotglossed)", "gogalking", "gohpot", "gold can",
    "goma irasuto", "gorgeous mushroom", "greatmosu", "greypidjun", "hakkasame", "hama chon", "hana ni nare", "happoubi jin", "harogen", "haze (ohw8g)",
    "healthyman", "henkuma", "henriiku (ahemaru)", "hershuar", "himanemuitoma", "himukai yuuji", "hintobento", "hiro (dismaless)", "hisakawa chin",
    "hiten (hitenkei)", "hizuki akira", "honjou raita", "hoo bamon", "hoshina meito", "housou-kun", "hungry clicker", "hxxg", "ie (raarami)", "ilya kuvshinov",
    "imaikuy0", "imoko (imonatsuki)", "in (ain)", "iro (mywife sunny)", "itomugi-kun", "itzah", "iuui", "izra", "izuru (timbermetal)", "jaemin107", "jema",
    "john kafka", "jtveemo", "juaag acgy", "jungon kim", "k-suwabe", "ka (996beshi)", "kabuyama kaigi", "kagami hirotaka", "kajimakoto", "kakure eria",
    "kamitani george", "kamiya yuu", "kan liu (666k)", "karyln", "kawacy", "kawakami rokkaku", "kazutake hazano", "kedama milk", "kekemotsu", "kenkou cross",
    "ki wa001", "kim eb", "kinkymation", "kito (sorahate)", "kittew", "kojima takeshi", "konoshige (ryuun)", "kotteri", "kousaki ruri", "krekkov",
    "krystopher decker", "kubo tite", "kunaboto", "kurumi (recycllamo)", "kusakanmuri", "kz oji", "lemon89h", "liduke", "ling s", "lloule", "love cacao",
    "m-da s-tarou", "machigami yoh", "mafuyu (chibi21)", "magion02", "mame", "mameojitan", "mamimi (mamamimi)", "mangshuo", "maria (maria rose)",
    "matanonki", "mato tsuyoi", "matra milan", "mazjojo", "menthako", "mento", "meme50", "merrytail", "merunyaa", "meyoco", "mgong520", "miclot",
    "mika pikazo", "mikami mika", "mikoyan", "mikozin", "mimonel", "min (120716)", "minaba hideo", "mina cream", "miraa (chikurin)", "misaka 12003-gou",
    "misaki toji", "mistermagnolia", "mitsu (mitsu art)", "miyoshi yoshimi", "miyuki ruria", "modare", "mochizuki kei", "mokottsu", "momo no sukebe",
    "momofuki rio", "momoko (momopoco)", "momomo (m0 3)", "momentcorefly", "morino hon", "mossacannibalis", "motono (sakamotono)", "motsuaki",
    "muk (monsieur)", "muloli", "murata range", "muromaki", "mx2j", "na tarapisu153", "nai ga", "nakare2845", "naku (naku999ziye)", "nama udon",
    "namaonpa", "namako daibakuhatsu", "namiki itsuki", "natsuiro xx", "neal d. anderson", "neekosiah", "nekololisama", "nevakuma (fanfanas)", "newey",
    "nidy", "ningen mame", "nixeu", "noir (ibaraki)", "nono (norabi)", "nora wanko", "norizc", "noyu (noyu23386566)", "nslacka", "null (nyanpyoun)",
    "nyamota", "nyantcha", "nyte tyde", "oastlv", "obiwan", "ohisashiburi", "omone hokoma agm", "onineko", "onnaski", "onono imoko", "oosaki shin'ya",
    "op na yarou", "orihara (ewkkyorhr)", "oskar vega", "otonoha aika", "owler", "past desiderium", "peargor", "penguin frontier", "pepoyo",
"personal ami", "pgm300", "pigeon666", "pija (pianiishimo)", "piromizu", "piratescat01", "pochi (pochi-goya)", "pokimari", "poper (arin sel)",
    "porforever", "poriuretan", "potemki11", "pottsness", "projecttiger", "pumpkinspicelatte", "qiandaiyiyu", "quasarcake", "r-urudo", "rakeemspoon",
    "raichiyo33", "raikoart", "ratatatat74", "re0n", "reia 76", "reido (reido c)", "reiq", "rei (sanbonzakura)", "rella", "relio db318", "remsrar",
    "rido (ridograph)", "rilex lenov", "ringeko-chan", "rinotuna", "robaato", "ronna", "ru zhai", "rune (dualhart)", "ruohire9", "rusky", "ryuuzaki ichi",
    "sam yang", "sanmen", "sciamano240", "sei shoujo", "seikatsu", "sencha (senta 10)", "shadman", "sheya", "shindol", "shinjiro", "shinonoko",
    "shion (mirudakemann)", "shiren (ourboy83)", "sho (sho lwlw)", "shunsuke", "shuz (dodidu)", "shycocoa", "simz", "siu (siu0207)", "skade",
    "slugbox", "smjim1986", "snatti", "snegovski", "so-bin", "soejima shigenori", "soleil (soleilmtfbwy03)", "solipsist", "soono (rlagpfl)", "stanley lau",
    "starshadowmagician", "studiopokotan", "sumaki shungo", "takarai shunsuke", "takeda hiromitsu", "tamomoko", "tangerine (dudu)", "tarakanovich", "taro-k",
    "terada tera", "thomasz", "tianliang duohe fangdongye", "tomatika", "toriyama akira", "toxxy", "tpi ri", "tsuaii", "tsunako", "turisasu", "uncle rabbit ii",
    "vanripper", "wagashi (dagashiya)", "wamudraws", "wanpaku pixels", "wanke", "watanabe tomari", "wlop", "wolrero", "wonbin lee", "yaguo", "yaigi",
    "yamamoto souichirou", "yao (pixiv9482697)", "yasuda suzuhito", "yasutak1192", "yd (orange maru)", "yoggi (stretchmen)", "yoko-chan (mijizukeyoko)",
    "yoko.u", "yomu (sgt epper)", "yoneyama mai", "yonketa", "yoru nai", "yoshizane akihiro", "yoya yogurt", "yufukiri", "yuji (fantasia)", "yuki (asayuki101)",
    "yukisame", "yunimaru", "yunoki itsugu", "yuyu (yuyuworks)", "z3zz4", "zankuro", "zefrableu", "zhibuji loom", "zounose", "zuizi", "zurikishi", "zutta"
];